version: '3'

services:
  postgres:
    image: docker.io/library/postgres:17.2-alpine
    restart: unless-stopped
    command: -c 'max_connections=128'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    image: docker.io/redis:alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 6379:6379

  migration:
    build:
      context: .
      dockerfile: Dockerfile
      target: migration
    env_file:
      - .env
    depends_on:                  
      postgres:
        condition: service_started
      redis: 
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    restart: unless-stopped
    volumes:
      - ./kslink.toml:/app/kslink.toml:ro
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on: 
      postgres:
        condition: service_started
      redis: 
        condition: service_started
      migration:
        condition: service_completed_successfully

volumes:
  postgres-data:
  pgo-profile:
