[default]
address = "0.0.0.0"
port = 8000
workers = 32

[default.database]
url = "postgres://postgres:postgres@postgres/postgres"
min_connections = 8
max_connections = 64
connect_timeout = 16

[default.redis]
url = "redis://redis:6379"
max_size = 64

[debug.database]
url = "postgres://postgres:postgres@localhost/postgres"

[debug.redis]
url = "redis://localhost:6379"
