[package]
name = "kslink-config"
version.workspace = true
edition.workspace = true

[dependencies]
educe.workspace = true
figment.workspace = true
rocket.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
