//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "visit_record")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub user_agent: String,
    pub ref_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::url_mapping::Entity",
        from = "Column::RefHash",
        to = "super::url_mapping::Column::Hash",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UrlMapping,
}

impl Related<super::url_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UrlMapping.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
