[package]
name = "entity"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
log.workspace = true
