type = "trim"

[tests]
"https://live.bilibili.com/?spm_id_from=333.1007.0.0" = "https://live.bilibili.com/?"

[content.'^https?://live\.bilibili\.com(?:/|$)']
explain = "Matching the live site of bilibili"

[content.'^https?://live\.bilibili\.com(?:/|$)'.param]
launch_id = "Which method user enter this live"
live_from = "Detail of method of the user enter this live"
session_id = "Tracing"
spm_id_from = '"Super Position Model" format'

[content.'^https?://(?:www\.)?bilibili\.com(?:/|$)']
explain = "Matching the main site of bilibili"

[content.'^https?://(?:www\.)?bilibili\.com(?:/|$)'.param]
spm_id_from = '"Super Position Model" format'
vd_source = "Share tracing"
