[package]
name = "kslink-frontend"
version.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
dioxus.workspace = true
reqwest.workspace = true
thiserror.workspace = true
url.workspace = true

[features]
default = ["web"]
web = ["dioxus/web"]
